version: '2'
services:
  tests: &base
    build:
      context: .
    image: keboola/phpunit-retry-annotations
  dev: &dev
    <<: *base
    volumes:
      - ./:/code
  dev-xdebug:
    <<: *dev
    build:
      context: docker/xdebug
    image: keboola/phpunit-retry-annotations-xdebug
    command: tail -f /dev/null
